### ISSUE TITLE
Redirect the netlify url to the custom url in the `netlify.toml`

### ISSUE THREAD

**Issue by travi** [travi/divops-slides#6]
```toml
[[redirects]]
from = "https://pragmatic-divops.netlify.com/*"
to = "https://pragmatic-divops.dev/:splat"
force = true
```
